// <auto-generated />
using System;
using BanCayTrong.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BanCayTrong.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231209174157_themtruong")]
    partial class themtruong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BanCayTrong.Models.CthoaDon", b =>
                {
                    b.Property<int>("Macthd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("macthd")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Dongia")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("dongia")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("Mahd")
                        .HasColumnName("mahd")
                        .HasColumnType("int");

                    b.Property<int>("Mamh")
                        .HasColumnName("mamh")
                        .HasColumnType("int");

                    b.Property<short?>("Soluong")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("soluong")
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("Thanhtien")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("thanhtien")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Macthd")
                        .HasName("PK__CTHoaDon__50C3A3F87C0C9776");

                    b.HasIndex("Mahd");

                    b.HasIndex("Mamh");

                    b.ToTable("CTHoaDon");
                });

            modelBuilder.Entity("BanCayTrong.Models.DanhMuc", b =>
                {
                    b.Property<int>("Madm")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("madm")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnName("ten")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Madm")
                        .HasName("PK__DanhMuc__7A21E0203D3BFB8B");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("BanCayTrong.Models.DiaChi", b =>
                {
                    b.Property<int>("Madc")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("madc")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Daxoa")
                        .HasColumnName("daxoa")
                        .HasColumnType("int");

                    b.Property<string>("Diachi1")
                        .IsRequired()
                        .HasColumnName("diachi")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("Macdinh")
                        .HasColumnName("macdinh")
                        .HasColumnType("int");

                    b.Property<int>("Makh")
                        .HasColumnName("makh")
                        .HasColumnType("int");

                    b.Property<string>("Phuongxa")
                        .IsRequired()
                        .HasColumnName("phuongxa")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Quanhuyen")
                        .IsRequired()
                        .HasColumnName("quanhuyen")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Tinhthanh")
                        .IsRequired()
                        .HasColumnName("tinhthanh")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Madc")
                        .HasName("PK__DiaChi__7A21E05AD6205090");

                    b.HasIndex("Makh");

                    b.ToTable("DiaChi");
                });

            modelBuilder.Entity("BanCayTrong.Models.HoaDon", b =>
                {
                    b.Property<int>("Mahd")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mahd")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Madc")
                        .HasColumnName("madc")
                        .HasColumnType("int");

                    b.Property<int>("Makh")
                        .HasColumnName("makh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnName("ngay")
                        .HasColumnType("datetime");

                    b.Property<int?>("Tongtien")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tongtien")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("Trangthai")
                        .HasColumnName("trangthai")
                        .HasColumnType("int");

                    b.HasKey("Mahd")
                        .HasName("PK__HoaDon__7A2100DE6AD41CD7");

                    b.HasIndex("Madc");

                    b.HasIndex("Makh");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("BanCayTrong.Models.KhachHang", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("makh")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Daxoa")
                        .HasColumnName("daxoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasColumnName("dienthoai")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Matkhau")
                        .HasColumnName("matkhau")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnName("ten")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Makh")
                        .HasName("PK__KhachHan__7A21BB4C8E5F63E9");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("BanCayTrong.Models.MatHang", b =>
                {
                    b.Property<int>("Mamh")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("mamh")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Daxoa")
                        .HasColumnName("daxoa")
                        .HasColumnType("int");

                    b.Property<int>("Giaban")
                        .HasColumnName("giaban")
                        .HasColumnType("int");

                    b.Property<int>("Giagoc")
                        .HasColumnName("giagoc")
                        .HasColumnType("int");

                    b.Property<string>("Hinhanh")
                        .HasColumnName("hinhanh")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("Madm")
                        .HasColumnName("madm")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasColumnName("mota")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("Soluong")
                        .HasColumnName("soluong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnName("ten")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Mamh")
                        .HasName("PK__MatHang__7A21CB8EA186BF2B");

                    b.HasIndex("Madm");

                    b.ToTable("MatHang");
                });

            modelBuilder.Entity("BanCayTrong.Models.NhanVien", b =>
                {
                    b.Property<int>("Manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("manv")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dienthoai")
                        .IsRequired()
                        .HasColumnName("dienthoai")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasColumnName("matkhau")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int?>("Quyen")
                        .HasColumnName("quyen")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnName("ten")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Manv")
                        .HasName("PK__NhanVien__7A21B37D3C91372E");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("BanCayTrong.Models.CthoaDon", b =>
                {
                    b.HasOne("BanCayTrong.Models.HoaDon", "MahdNavigation")
                        .WithMany("CthoaDon")
                        .HasForeignKey("Mahd")
                        .HasConstraintName("FK__CTHoaDon__mahd__59FA5E80")
                        .IsRequired();

                    b.HasOne("BanCayTrong.Models.MatHang", "MamhNavigation")
                        .WithMany("CthoaDon")
                        .HasForeignKey("Mamh")
                        .HasConstraintName("FK__CTHoaDon__mamh__5AEE82B9")
                        .IsRequired();
                });

            modelBuilder.Entity("BanCayTrong.Models.DiaChi", b =>
                {
                    b.HasOne("BanCayTrong.Models.KhachHang", "MakhNavigation")
                        .WithMany("DiaChi")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK__DiaChi__makh__5070F446")
                        .IsRequired();
                });

            modelBuilder.Entity("BanCayTrong.Models.HoaDon", b =>
                {
                    b.HasOne("BanCayTrong.Models.DiaChi", "MadcNavigation")
                        .WithMany("HoaDon")
                        .HasForeignKey("Madc")
                        .HasConstraintName("FK__HoaDon__madc__571DF1D5")
                        .IsRequired();

                    b.HasOne("BanCayTrong.Models.KhachHang", "MakhNavigation")
                        .WithMany("HoaDon")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK__HoaDon__makh__5629CD9C")
                        .IsRequired();
                });

            modelBuilder.Entity("BanCayTrong.Models.MatHang", b =>
                {
                    b.HasOne("BanCayTrong.Models.DanhMuc", "MadmNavigation")
                        .WithMany("MatHang")
                        .HasForeignKey("Madm")
                        .HasConstraintName("FK__MatHang__madm__4BAC3F29")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
